- htdocs/display.php
> Check that pwdMaxAge is not 0 before computing expiration

- templates/display.tpl
> Set Smarty code outside inputs

- conf/config.inc.php
- docs/attributes.rst
- htdocs/index.php
- lang/en.inc.php
- lang/fr.inc.php
- lib/filesize.inc.php
- lib/smarty.inc.php
- templates/value_displayer.tpl
This contribution allows to display a value representing bytes and convert it in a human readable form
references #10
> Display and convert bytes value

- conf/config.inc.php
- docs/index.rst
- docs/posthook.rst
- htdocs/display.php
- htdocs/resetpassword.php
- lib/posthook.inc.php
- templates/display.tpl
Possibilty to use a posthook script, like in Self Service Password
References #9
> Posthook feature

- htdocs/display.php
…ion is not set or is equal to 0
> Handle the case where pwdAccountLockedTime is set but pwdLockoutDuration is not set or is equal to 0

- conf/config.inc.php
- docs/index.rst
- docs/lockaccount.rst
- htdocs/display.php
- htdocs/index.php
- htdocs/lockaccount.php
- lang/en.inc.php
- lang/fr.inc.php
- templates/display.tpl
This pull request introduces a feature to lock account permanently
it resolves #16
> Lock account

- conf/config.inc.php
- docs/display-parameters.rst
- htdocs/display.php
- htdocs/index.php
- lang/en.inc.php
- lang/fr.inc.php
- templates/display.tpl
> Display expiration date

- conf/config.inc.php
- htdocs/index.php
- packaging/debian/replace_cache_dirs
- packaging/debian/rules
- packaging/debian/service-desk.dirs
- packaging/rpm/SPECS/service-desk.spec
> Move cache dirs in /var

- Dockerfile
- docs/installation.rst
- packaging/README
- packaging/docker/Dockerfile
as discussed in https://github.com/ltb-project/service-desk/issues/31
re-using Dockerfile from self-service-password
> feat(docker)

- conf/config.inc.php
- docs/dashboards.rst
- htdocs/index.php
- htdocs/searchwillexpire.php
- lang/en.inc.php
- lang/fr.inc.php
- templates/menu.tpl
- templates/searchwillexpire.tpl
A new page that displays accounts with password that will soon expire
> Dashboard will expire passwords

- htdocs/display.php
- htdocs/lockaccount.php
Don't lock account until a valid ppolicy with pwdLockout=TRUE is associated (#45)
> Don't lock account until a valid ppolicy with pwdLockout=TRUE is associated (#45)

- htdocs/display.php
> Check that values is an array before parsing it

- conf/config.inc.php
- docs/resetpassword.rst
- htdocs/index.php
- templates/display.tpl
> Disable reset choice button

- conf/config.inc.php
- docs/attributes.rst
- htdocs/index.php
- lib/smarty.inc.php
- templates/value_displayer.tpl
Split address on `$` separator
> Address displayer

- htdocs/index.php
> Missing replacement for lang value (issue #92)

- docs/audit.rst
- docs/config_mail.rst
Improvement of the audit trail documentation and typo fix in mail config.
> Some documentation improvements

- docs/audit.rst
- lib/audit.inc.php
> Add IP in audit

- htdocs/lockaccount.php
- htdocs/unlockaccount.php
There was no result code when lock and unlock actions are successful
> Provide result codes for lock/unlock account actions

- conf/config.inc.php
- lib/detectbrowserlanguage.php
> Replace deprecated FILTER_SANITIZE_STRING constant

- conf/config.inc.php
- docs/general-parameters.rst
- htdocs/index.php
> add an option for defining the timezone (#110)

- conf/config.inc.php
- docs/ldap-parameters.rst
- htdocs/display.php
- htdocs/index.php
- lang/en.inc.php
- lang/fr.inc.php
- templates/value_displayer.tpl
Solve #53 
Just print the cn value of the corresponding ppolicy configuration object
> Display pwdpolicysubentry

- conf/config.inc.php
- docs/general-parameters.rst
- htdocs/index.php
- lib/detectbrowserlanguage.php
> #124: Adding allowed_lang configuration.

- composer.json
> update ltb-ldap library name to ltb-common (#147)

- conf/config.inc.php
- docs/ldap-parameters.rst
- htdocs/search.php
- htdocs/searchexpired.php
- htdocs/searchidle.php
- htdocs/searchlocked.php
- htdocs/searchwillexpire.php
> make all search functions to use a scope (#144)

- conf/.gitignore
> add .gitignore in conf directory (#143)

- conf/config.inc.php
- docs/general-parameters.rst
- htdocs/index.php
> remove verbose smarty logs, unless smarty_debug == true (#159)

- conf/config.inc.php
- docs/ldap-parameters.rst
- docs/upgrade.rst
- htdocs/index.php
> Use page size parameter from ltb-common (#165)

- htdocs/display.php
- templates/display.tpl
> 187 show error when disabling account

- composer.json
- htdocs/display.php
This requires a new version of ltb-common to use getStartDate and getEndDate methods
> Manage Active Directory special values for accountExpires

- templates/display.tpl
> Fix bad condition for posthookenableresult

- htdocs/updatevaliditydates.php
When date is empty, remove value in attribute
> Manage empty values for start date and end date

- htdocs/resetpassword.php
> Admin notification does not replace dn

- htdocs/css/service-desk.css
- templates/auditlog.tpl
- templates/footer.tpl
- templates/search.tpl
- templates/searchdisabled.tpl
- templates/searchexpired.tpl
- templates/searchidle.tpl
- templates/searchinvalid.tpl
- templates/searchlocked.tpl
- templates/searchwillexpire.tpl
- templates/spinner.tpl
The dataTable is now shown only when loaded
> Spinner to wait for dataTable loading

- lib/date.inc.php
> fix empty values for ad_date (#232)

- docs/general-parameters.rst
- htdocs/index.php
> Inject configuration variables in templates

- conf/config.inc.php
- docs/general-parameters.rst
- htdocs/index.php
- templates/header.tpl
> Favicon configuration

- composer.json
- js-templates/display_status_attributes_list.html
- js-templates/display_user_attributes_list.html
- templates/create.tpl
- templates/datatables-audit.js.tpl
- templates/datatables-search.js.tpl
- templates/display.tpl
- templates/footer.tpl
- templates/header.tpl
- templates/rename.tpl
- templates/update.tpl
- templates/value-displayer.js.tpl
> Use bootstrap grid/flex to replace table in update page

- docs/customization.rst
- htdocs/js/value-renderer.js
> refactor get_config_js function (#260)

- docs/customization.rst
- htdocs/api/search-api.php
- htdocs/index.php
- htdocs/js/value-renderer.js
- js-templates/ldapStaticlistTypeRenderer.html
- templates/auditlog-value-displayer.js.tpl
> 250 fix list value display
